In [3]:
import numpy as np


In [2]:
pip install numpy


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 3.7 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
a = [1,2,3,4]
b= np.array(a)
b

array([1, 2, 3, 4])

In [5]:
a = []
size = int(input("enter the size"))
for i in range(size):
    val =int(input("enter number"))
    a.append(val)

print(a) 
b= np.array(a)
b   

[12, 45, 56, 74, 12]


array([12, 45, 56, 74, 12])

In [6]:
# 2d array 
a= [[1,2,3],[4,5,6],[7,8,9]]
b= np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print("total dimension",b.ndim)
print("shape of an array",b.shape)
print("total elements",b.size)

total dimension 2
shape of an array (3, 3)
total elements 9


In [8]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [9]:
b= np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# ones 
a = np.ones(3)
a
b= np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
matrix = np.eye(3)
print(matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
b= np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [16]:
# diagonal matrix 
a= np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [17]:
# radiant 
a = np.random.randint(1,10,3)
a

array([8, 4, 2])

In [18]:
a =np.random.rand(5)
a

array([0.94882132, 0.5261928 , 0.84175265, 0.92350379, 0.59626721])

In [19]:
a =np.random.randn(5)
a

array([-1.72778023,  0.98635596, -0.88737694, -0.65350507, -0.32828307])

In [20]:
a=  np.random.randint(1,50,12)
a

array([37, 38, 38, 45, 41, 30, 38, 45,  8, 23, 47, 31])

In [ ]:
a = 

In [22]:
a.reshape(2,6)

array([[37, 38, 38, 45, 41, 30],
       [38, 45,  8, 23, 47, 31]])

In [23]:
a.reshape(3,4)

array([[37, 38, 38, 45],
       [41, 30, 38, 45],
       [ 8, 23, 47, 31]])

In [ ]:
# principal of -1 find the row or column by itself 
a = a.reshape(-1,4)
a

array([[37, 38, 38, 45],
       [41, 30, 38, 45],
       [ 8, 23, 47, 31]])

In [25]:
# principal of -1
a = a.reshape(-1,6)
a

array([[37, 38, 38, 45, 41, 30],
       [38, 45,  8, 23, 47, 31]])

In [37]:
# seed function 
# once data in cretated and it fixes it 
np.random.seed(2)
a =np.random.randint(1,100,10)
a 

array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50])

In [39]:
# view vs copy 
a= np.array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50])
b= a[3:6]
b[:]=0
a

array([41, 16, 73,  0,  0,  0, 76,  8, 35, 50])

In [40]:
a= np.array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50])
b= a[3:6].copy()
b[:]=0
a

array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50])

In [41]:
# operations onn array 
a  = np.arange(1,5)
print(a)
print(a*2)

[1 2 3 4]
[2 4 6 8]


In [42]:
a +2


array([3, 4, 5, 6])

In [43]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [44]:
b = np.array([7,6,5,4]).reshape(2,2)
b

array([[7, 6],
       [5, 4]])

In [45]:
a +b

array([[8, 8],
       [8, 8]])

In [ ]:
a.dot(b) # for matric multiplication

array([[17, 14],
       [41, 34]])

In [47]:
np.min(a)

np.int64(1)

In [48]:
np.max(a)

np.int64(4)

In [ ]:
np.argmin(a) # retuen the index of the min value 


np.int64(0)

In [50]:
np.argmax(a)

np.int64(3)

In [51]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [52]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [55]:
# linspace method
import numpy as np

a = np.linspace(1, 2, 5)
print(a)


[1.   1.25 1.5  1.75 2.  ]


In [56]:
a = np.linspace(1, 2, 5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [57]:
# np.unique
a= np.array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50])
np.unique(a, return_index= True,return_counts= True)


(array([ 8, 16, 23, 35, 41, 44, 50, 73, 76, 83]),
 array([7, 1, 3, 8, 0, 4, 9, 2, 6, 5]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [ ]:

a =np.array([1,2,3,4])

b =np.array([1,21,30,41])

c =np.array([10,23,31,4])

In [59]:
# Q creating an array
a = np.random.randint(10)
a

1

In [60]:

zeros_array = np.zeros((2, 3))  # 2 rows, 3 columns
print("Zeros array:\n", zeros_array)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [61]:

array = np.array([10, 20, 30, 40, 50])
print("Array created using NumPy:", array)


Array created using NumPy: [10 20 30 40 50]


In [67]:
array = np.random.rand(10)
print(array)

a1 = np.array("array are",array)
print(a1)


[0.06714437 0.99385201 0.97058031 0.80025835 0.60181712 0.76495986
 0.16922545 0.29302323 0.52406688 0.35662428]


TypeError: Cannot construct a dtype from an array

In [71]:
pip install pandas


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 979.7 kB/s eta 0:00:0000:01:01
Note: you may need to restart the kernel to use updated packages.


In [72]:
import pandas as pd

In [74]:
a = {
    "cgpa":[7,8,9,8,9],
    "resume_score":[9,9,9,8,8],
    "placed":[1,0,0,1,1]

}

In [75]:
df = pd.DataFrame(a)
df

cgpa  resume_score  placed
0     7             9       1
1     8             9       0
2     9             9       0
3     8             8       1
4     9             8       1

In [84]:
df.to_csv(".venv/class.csv")

OSError: Cannot save file into a non-existent directory: 'excel'

In [77]:
df = pd.read_csv('services.csv')

In [ ]:
df

In [79]:
df.shape

(23, 22)

In [ ]:
df.info()

In [ ]:
df.head()

In [83]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [85]:
df.describe()

id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
25%     6.50000     6.500000         NaN
50%    12.00000    12.000000         NaN
75%    17.50000    17.500000         NaN
max    23.00000    22.000000         NaN

In [86]:
top_left_corner_df = df.iloc[:4,:3]
top_left_corner_df

id  location_id  program_id
0   1            1         NaN
1   2            2         NaN
2   3            3         NaN
3   4            4         NaN

In [87]:
df.loc[1:3,['id',"fees"]]

id                                               fees
1   2  None. Donations requested of clients who can a...
2   3                                              None.
3   4  Vary according to income ($5-$90). Cash, check...

In [89]:
s = df.axes
s

[RangeIndex(start=0, stop=23, step=1),
 Index(['id', 'location_id', 'program_id', 'accepted_payments',
        'alternate_name', 'application_process', 'audience', 'description',
        'eligibility', 'email', 'fees', 'funding_sources',
        'interpretation_services', 'keywords', 'languages', 'name',
        'required_documents', 'service_areas', 'status', 'wait_time', 'website',
        'taxonomy_ids'],
       dtype='object')]

In [90]:
df.empty

False

In [91]:
df.isnull().sum()

id                          0
location_id                 0
program_id                 23
accepted_payments          22
alternate_name             22
application_process         0
audience                    9
description                 0
eligibility                 6
email                      22
fees                        2
funding_sources             2
interpretation_services    22
keywords                    2
languages                  22
name                        0
required_documents         22
service_areas               2
status                      0
wait_time                   4
website                    21
taxonomy_ids               22
dtype: int64

In [ ]:
# for i in df.columns:
#     df[i] = df[i].fillna(df[i].mean())

In [ ]:
df.values

In [99]:
p = df.sort_values(by ="location_id")
p

id  location_id  program_id         accepted_payments  \
0    1            1         NaN                       NaN   
1    2            2         NaN                       NaN   
2    3            3         NaN                       NaN   
3    4            4         NaN                       NaN   
4    5            5         NaN                       NaN   
5    6            6         NaN                       NaN   
6    7            7         NaN                       NaN   
7    8            8         NaN                       NaN   
8    9            9         NaN                       NaN   
9   10           10         NaN                       NaN   
10  11           11         NaN                       NaN   
11  12           12         NaN                       NaN   
12  13           13         NaN                       NaN   
13  14           14         NaN                       NaN   
14  15           15         NaN                       NaN   
15  16           16         NaN                       NaN   
16  17           17         NaN                       NaN   
17  18           18         NaN                       NaN   
18  19           19         NaN                       NaN   
19  20           20         NaN                       NaN   
20  21           21         NaN                       NaN   
21  22           22         NaN  Cash, Check, Credit Card   
22  23           22         NaN                       NaN   

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.   
1                     NaN                 Apply by phone for an appointment.   
2                     NaN        Phone for information (403-4300 Ext. 4322).   
3                     NaN                                    Apply by phone.   
4                     NaN                             Phone for information.   
5                     NaN  Walk in or apply by phone for membership appli...   
6                     NaN  Apply by phone or be referred by a doctor, soc...   
7                     NaN                                    Apply by phone.   
8                     NaN  Walk in. Proof of residency in California requ...   
9                     NaN  Walk in. Proof of California residency to rece...   
10                    NaN  Walk in. Proof of California residency require...   
11                    NaN  Walk in or apply by phone, email or webpage re...   
12                    NaN  Walk in. Proof of California residency require...   
13                    NaN  Call for appointment. Referral from human serv...   
14                    NaN          Walk in or through other agency referral.   
15                    NaN  Walk in. Written application, identification r...   
16                    NaN                              Call for information.   
17                    NaN  Call for screening appointment. Medical visits...   
18                    NaN     Call for screening appointment (650-347-3648).   
19                    NaN                                           Walk in.   
20                    NaN                    By phone during business hours.   
21  Fotos para pasaportes                  Walk in or apply by phone or mail   
22                    NaN                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
3   Parents, children, families with problems of c...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, ...   
7   Senior citizens age 60 or over, disabled indiv...   
8      Ethnic minorities, especially Spanish speaking   
9                                               

In [100]:
df['location_id']=df['location_id'].astype(float)

In [101]:
df

id  location_id  program_id         accepted_payments  \
0    1          1.0         NaN                       NaN   
1    2          2.0         NaN                       NaN   
2    3          3.0         NaN                       NaN   
3    4          4.0         NaN                       NaN   
4    5          5.0         NaN                       NaN   
5    6          6.0         NaN                       NaN   
6    7          7.0         NaN                       NaN   
7    8          8.0         NaN                       NaN   
8    9          9.0         NaN                       NaN   
9   10         10.0         NaN                       NaN   
10  11         11.0         NaN                       NaN   
11  12         12.0         NaN                       NaN   
12  13         13.0         NaN                       NaN   
13  14         14.0         NaN                       NaN   
14  15         15.0         NaN                       NaN   
15  16         16.0         NaN                       NaN   
16  17         17.0         NaN                       NaN   
17  18         18.0         NaN                       NaN   
18  19         19.0         NaN                       NaN   
19  20         20.0         NaN                       NaN   
20  21         21.0         NaN                       NaN   
21  22         22.0         NaN  Cash, Check, Credit Card   
22  23         22.0         NaN                       NaN   

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.   
1                     NaN                 Apply by phone for an appointment.   
2                     NaN        Phone for information (403-4300 Ext. 4322).   
3                     NaN                                    Apply by phone.   
4                     NaN                             Phone for information.   
5                     NaN  Walk in or apply by phone for membership appli...   
6                     NaN  Apply by phone or be referred by a doctor, soc...   
7                     NaN                                    Apply by phone.   
8                     NaN  Walk in. Proof of residency in California requ...   
9                     NaN  Walk in. Proof of California residency to rece...   
10                    NaN  Walk in. Proof of California residency require...   
11                    NaN  Walk in or apply by phone, email or webpage re...   
12                    NaN  Walk in. Proof of California residency require...   
13                    NaN  Call for appointment. Referral from human serv...   
14                    NaN          Walk in or through other agency referral.   
15                    NaN  Walk in. Written application, identification r...   
16                    NaN                              Call for information.   
17                    NaN  Call for screening appointment. Medical visits...   
18                    NaN     Call for screening appointment (650-347-3648).   
19                    NaN                                           Walk in.   
20                    NaN                    By phone during business hours.   
21  Fotos para pasaportes                  Walk in or apply by phone or mail   
22                    NaN                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
3   Parents, children, families with problems of c...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, ...   
7   Senior citizens age 60 or over, disabled indiv...   
8      Ethnic minorities, especially Spanish speaking   
9                                               

In [102]:
df['location_id']=df['location_id'].add(10)
df

id  location_id  program_id         accepted_payments  \
0    1         11.0         NaN                       NaN   
1    2         12.0         NaN                       NaN   
2    3         13.0         NaN                       NaN   
3    4         14.0         NaN                       NaN   
4    5         15.0         NaN                       NaN   
5    6         16.0         NaN                       NaN   
6    7         17.0         NaN                       NaN   
7    8         18.0         NaN                       NaN   
8    9         19.0         NaN                       NaN   
9   10         20.0         NaN                       NaN   
10  11         21.0         NaN                       NaN   
11  12         22.0         NaN                       NaN   
12  13         23.0         NaN                       NaN   
13  14         24.0         NaN                       NaN   
14  15         25.0         NaN                       NaN   
15  16         26.0         NaN                       NaN   
16  17         27.0         NaN                       NaN   
17  18         28.0         NaN                       NaN   
18  19         29.0         NaN                       NaN   
19  20         30.0         NaN                       NaN   
20  21         31.0         NaN                       NaN   
21  22         32.0         NaN  Cash, Check, Credit Card   
22  23         32.0         NaN                       NaN   

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.   
1                     NaN                 Apply by phone for an appointment.   
2                     NaN        Phone for information (403-4300 Ext. 4322).   
3                     NaN                                    Apply by phone.   
4                     NaN                             Phone for information.   
5                     NaN  Walk in or apply by phone for membership appli...   
6                     NaN  Apply by phone or be referred by a doctor, soc...   
7                     NaN                                    Apply by phone.   
8                     NaN  Walk in. Proof of residency in California requ...   
9                     NaN  Walk in. Proof of California residency to rece...   
10                    NaN  Walk in. Proof of California residency require...   
11                    NaN  Walk in or apply by phone, email or webpage re...   
12                    NaN  Walk in. Proof of California residency require...   
13                    NaN  Call for appointment. Referral from human serv...   
14                    NaN          Walk in or through other agency referral.   
15                    NaN  Walk in. Written application, identification r...   
16                    NaN                              Call for information.   
17                    NaN  Call for screening appointment. Medical visits...   
18                    NaN     Call for screening appointment (650-347-3648).   
19                    NaN                                           Walk in.   
20                    NaN                    By phone during business hours.   
21  Fotos para pasaportes                  Walk in or apply by phone or mail   
22                    NaN                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
3   Parents, children, families with problems of c...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, ...   
7   Senior citizens age 60 or over, disabled indiv...   
8      Ethnic minorities, especially Spanish speaking   
9                                               

In [107]:
df = df.drop(columns=['email'],axis=1)
df

KeyError: "['email'] not found in axis"

In [ ]:
df = df.drop(columns=['accepted_payments'],axis=1)
df

id  location_id  program_id  \
0    1         11.0         NaN   
1    2         12.0         NaN   
2    3         13.0         NaN   
3    4         14.0         NaN   
4    5         15.0         NaN   
5    6         16.0         NaN   
6    7         17.0         NaN   
7    8         18.0         NaN   
8    9         19.0         NaN   
9   10         20.0         NaN   
10  11         21.0         NaN   
11  12         22.0         NaN   
12  13         23.0         NaN   
13  14         24.0         NaN   
14  15         25.0         NaN   
15  16         26.0         NaN   
16  17         27.0         NaN   
17  18         28.0         NaN   
18  19         29.0         NaN   
19  20         30.0         NaN   
20  21         31.0         NaN   
21  22         32.0         NaN   
22  23         32.0         NaN   

                                  application_process  \
0                          Walk in or apply by phone.   
1                  Apply by phone for an appointment.   
2         Phone for information (403-4300 Ext. 4322).   
3                                     Apply by phone.   
4                              Phone for information.   
5   Walk in or apply by phone for membership appli...   
6   Apply by phone or be referred by a doctor, soc...   
7                                     Apply by phone.   
8   Walk in. Proof of residency in California requ...   
9   Walk in. Proof of California residency to rece...   
10  Walk in. Proof of California residency require...   
11  Walk in or apply by phone, email or webpage re...   
12  Walk in. Proof of California residency require...   
13  Call for appointment. Referral from human serv...   
14          Walk in or through other agency referral.   
15  Walk in. Written application, identification r...   
16                              Call for information.   
17  Call for screening appointment. Medical visits...   
18     Call for screening appointment (650-347-3648).   
19                                           Walk in.   
20                    By phone during business hours.   
21                  Walk in or apply by phone or mail   
22                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
3   Parents, children, families with problems of c...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, ...   
7   Senior citizens age 60 or over, disabled indiv...   
8      Ethnic minorities, especially Spanish speaking   
9                                                 NaN   
10                                                NaN   
11  Adults, parents, children in 1st-12th grades i...   
12                                                NaN   
13  Individuals or families with low or no income ...   
14  Adult alcoholic/drug addictive men and women w...   
15                                                NaN   
16                                                NaN   
17                                                NaN   
18                                                NaN   
19                                                NaN   
20                                                NaN   
21  Profit and nonprofit businesses, the public, m...   
22  Second service and nonprofit businesses, the p...   

                                          description  \
0   A walk-in center for older adults that provide...   
1   Provides training and job placement to eligibl...   
2   Offers supportive counseling services to San M...   
3   Provides supervised visitation services and a ...   
4   Provides fixed 8% short term loans to eligible...   
5   A multipurpose center offering a wide variety ...   
6   Rosener House is a day

In [110]:
p =df.rename(columns= {'location_id':'new_location'})
p

id  new_location  program_id  \
0    1          11.0         NaN   
1    2          12.0         NaN   
2    3          13.0         NaN   
3    4          14.0         NaN   
4    5          15.0         NaN   
5    6          16.0         NaN   
6    7          17.0         NaN   
7    8          18.0         NaN   
8    9          19.0         NaN   
9   10          20.0         NaN   
10  11          21.0         NaN   
11  12          22.0         NaN   
12  13          23.0         NaN   
13  14          24.0         NaN   
14  15          25.0         NaN   
15  16          26.0         NaN   
16  17          27.0         NaN   
17  18          28.0         NaN   
18  19          29.0         NaN   
19  20          30.0         NaN   
20  21          31.0         NaN   
21  22          32.0         NaN   
22  23          32.0         NaN   

                                  application_process  \
0                          Walk in or apply by phone.   
1                  Apply by phone for an appointment.   
2         Phone for information (403-4300 Ext. 4322).   
3                                     Apply by phone.   
4                              Phone for information.   
5   Walk in or apply by phone for membership appli...   
6   Apply by phone or be referred by a doctor, soc...   
7                                     Apply by phone.   
8   Walk in. Proof of residency in California requ...   
9   Walk in. Proof of California residency to rece...   
10  Walk in. Proof of California residency require...   
11  Walk in or apply by phone, email or webpage re...   
12  Walk in. Proof of California residency require...   
13  Call for appointment. Referral from human serv...   
14          Walk in or through other agency referral.   
15  Walk in. Written application, identification r...   
16                              Call for information.   
17  Call for screening appointment. Medical visits...   
18     Call for screening appointment (650-347-3648).   
19                                           Walk in.   
20                    By phone during business hours.   
21                  Walk in or apply by phone or mail   
22                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
3   Parents, children, families with problems of c...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, ...   
7   Senior citizens age 60 or over, disabled indiv...   
8      Ethnic minorities, especially Spanish speaking   
9                                                 NaN   
10                                                NaN   
11  Adults, parents, children in 1st-12th grades i...   
12                                                NaN   
13  Individuals or families with low or no income ...   
14  Adult alcoholic/drug addictive men and women w...   
15                                                NaN   
16                                                NaN   
17                                                NaN   
18                                                NaN   
19                                                NaN   
20                                                NaN   
21  Profit and nonprofit businesses, the public, m...   
22  Second service and nonprofit businesses, the p...   

                                          description  \
0   A walk-in center for older adults that provide...   
1   Provides training and job placement to eligibl...   
2   Offers supportive counseling services to San M...   
3   Provides supervised visitation services and a ...   
4   Provides fixed 8% short term loans to eligible...   
5   A multipurpose center offering a wide variety ...   
6 